# Generated by Django 6.1.1 on 2026-09-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_libraryentry_unique_user_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
